{% set name = "opentelemetry-instrumentation-tornado" %}
{% set version = "0.44b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_tornado-{{ version }}.tar.gz
  sha256: ef58250d1b91efd4c581d3010673a02ce8e9f8bf7f8860b20f4f5b1b6bd05cad

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.44b0
    - opentelemetry-semantic-conventions ==0.44b0
    - opentelemetry-util-http ==0.44b0
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-tornado 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-tornado 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-tornado 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-tornado 
    # - http-server-mock 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-tornado 
    # - http-server-mock 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-tornado 
    # - http-server-mock 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-tornado 
    # - http-server-mock 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-tornado 
    # - http-server-mock 

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-tornado
  summary: Tornado instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
