{% set name = "opentelemetry-instrumentation-tornado" %}
{% set version = "0.49b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_tornado-{{ version }}.tar.gz
  sha256: 745a31b8d2e799a0d67318515d60379e9e5812a9f3907b8f1ae27cca6cc2b81d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.49b2
    - opentelemetry-semantic-conventions ==0.49b2
    - opentelemetry-util-http ==0.49b2
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-tornado 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-tornado 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-tornado 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-instrumentation-tornado 
    # - http-server-mock 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-instrumentation-tornado 
    # - http-server-mock 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-instrumentation-tornado 
    # - http-server-mock 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.43b0
    # - opentelemetry-instrumentation-tornado 
    # - http-server-mock 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.44b0
    # - opentelemetry-instrumentation-tornado 
    # - http-server-mock 
    # - tornado >=5.1.1
    # - tornado >=5.1.1
    # - tornado >=5.1.1
    # - tornado >=5.1.1
    # - tornado >=5.1.1
    # - tornado >=5.1.1
    # - tornado >=5.1.1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-tornado
  summary: Tornado instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
