{% set name = "opentelemetry-instrumentation-tornado" %}
{% set version = "0.39b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_tornado-{{ version }}.tar.gz
  sha256: 20d890cfd7ae12c91cc627e424762fdc6ea630bda18ecfa0ce3d6331d8e439c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.39b0
    - opentelemetry-semantic-conventions ==0.39b0
    - opentelemetry-util-http ==0.39b0
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-instrumentation-tornado 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-instrumentation-tornado 
    # - tornado >=5.1.1
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-instrumentation-tornado 

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-tornado
  summary: Tornado instrumentation for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
